import { useState } from 'react';
import type { Application, ApplicationStatus, ReminderInterval } from '../../api/types';
import { REMIND_LABELS, STATUS_LABELS } from '../../utils/constants';
import styles from './Tracker.module.css';

export interface TrackerFilters { company: string; title: string; location: string; status: string; deadline: string; reminder: string; applied: string; notes: string; }
const labels: Record<string, string> = { company: 'Company', title: 'Title', location: 'Location', status: 'Status', deadline: 'Deadline', remind: 'Remind', applied: 'Applied', notes: 'Notes' };
type Update = (id: string | number, patch: Partial<Application>) => Promise<void>;

export function TrackerTable({ items, columns, filters, onFilter, sort, onSort, onUpdate, onDelete }: { items: Application[]; columns: string[]; filters: TrackerFilters; onFilter: <K extends keyof TrackerFilters>(key: K, value: TrackerFilters[K]) => void; sort: { column: string; direction: 1 | -1 }; onSort: (column: string) => void; onUpdate: Update; onDelete: (id: string | number) => Promise<void> }) {
  return <div className={styles.tableWrap}><table><thead><tr><th aria-label="Delete" />{columns.map((column) => <th key={column}><button onClick={() => onSort(column)}>{labels[column]} {sort.column === column && (sort.direction === 1 ? '▲' : '▼')}</button></th>)}<th aria-label="Open details" /></tr><tr className={styles.filterRow}><th />{columns.map((column) => <th key={column}>{filterControl(column, filters, onFilter)}</th>)}<th /></tr></thead><tbody>{items.map((app) => <TrackerRow key={app.id} app={app} columns={columns} onUpdate={onUpdate} onDelete={onDelete} />)}</tbody></table>{!items.length && <p className={styles.noResults}>No applications match these filters.</p>}</div>;
}
function filterControl(column: string, filters: TrackerFilters, onFilter: <K extends keyof TrackerFilters>(key: K, value: TrackerFilters[K]) => void) {
  if (column === 'status') return <select value={filters.status} onChange={(e) => onFilter('status', e.target.value)}><option value="">All</option>{Object.entries(STATUS_LABELS).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select>;
  if (column === 'remind') return <select value={filters.reminder} onChange={(e) => onFilter('reminder', e.target.value)}><option value="">All</option>{Object.entries(REMIND_LABELS).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select>;
  if (column === 'deadline' || column === 'applied') return <input type="date" value={filters[column]} onChange={(e) => onFilter(column, e.target.value)} />;
  const key = column as 'company' | 'title' | 'location' | 'notes';
  return <input value={filters[key]} placeholder="Filter…" onChange={(e) => onFilter(key, e.target.value)} />;
}
function TrackerRow({ app, columns, onUpdate, onDelete }: { app: Application; columns: string[]; onUpdate: Update; onDelete: (id: string | number) => Promise<void> }) {
  const [expanded, setExpanded] = useState(false);
  return <><tr><td><button className={styles.deleteButton} onClick={() => { if (window.confirm(`Remove ${app.title}?`)) void onDelete(app.id); }} aria-label={`Remove ${app.title}`}>×</button></td>{columns.map((column) => <td key={column}>{cell(app, column, onUpdate)}</td>)}<td><button onClick={() => setExpanded(!expanded)}>{expanded ? 'Less' : 'More'}</button></td></tr>{expanded && <tr className={styles.detailRow}><td colSpan={columns.length + 2}><dl><dt>Pay</dt><dd>{app.pay || '—'}</dd>{app.url && <><dt>Link</dt><dd><a href={app.url} target="_blank" rel="noreferrer">Open posting</a></dd></>}<dt>Status</dt><dd>{STATUS_LABELS[app.status]}</dd></dl></td></tr>}</>;
}
function cell(app: Application, column: string, onUpdate: Update) { const update = (patch: Partial<Application>) => void onUpdate(app.id, patch); switch (column) { case 'company': return app.company; case 'title': return app.url ? <a href={app.url} target="_blank" rel="noreferrer">{app.title}</a> : app.title; case 'location': return app.location || '—'; case 'status': return <select value={app.status} onChange={(e) => update({ status: e.target.value as ApplicationStatus })}>{Object.entries(STATUS_LABELS).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select>; case 'deadline': return <input type="date" value={app.deadline || ''} onChange={(e) => update({ deadline: e.target.value })} />; case 'remind': return <select value={app.reminder_interval || 'daily'} onChange={(e) => update({ reminder_interval: e.target.value as ReminderInterval })}>{Object.entries(REMIND_LABELS).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select>; case 'applied': return <input type="date" value={app.applied_at || ''} onChange={(e) => update({ applied_at: e.target.value })} />; case 'notes': return <input className={styles.notesInput} defaultValue={app.notes || ''} placeholder="Add notes…" onBlur={(e) => update({ notes: e.target.value })} />; default: return null; } }
