import { useState } from 'react';
import { useCompaniesStore } from '../../store/companies';
import { useJobsStore } from '../../store/jobs';
import { usePreferencesStore } from '../../store/preferences';
import { COLUMN_DEFAULTS } from '../../utils/constants';
import styles from './Scanner.module.css';
const groups = [{ key: 'level', label: 'Level', values: ['intern','fellow','apprentice','entry','mid','senior+','manager+'] }, { key: 'payType', label: 'Pay', values: ['hourly','salary'] }, { key: 'schedule', label: 'Schedule', values: ['full-time','part-time','contract'] }] as const;
export function FilterBar({ sources, hiddenCount }: { sources: string[]; hiddenCount: number }) {
  const [open, setOpen] = useState<string | null>(null); const { filters, setFilter, columns, setColumnVisibility, savedFilters, saveFilterPreset, loadFilterPreset, deleteFilterPreset } = usePreferencesStore(); const favJobs = useJobsStore(s => s.favJobIds); const favEmployers = useCompaniesStore(s => s.favEmployers);
  const toggle = (key: 'level'|'payType'|'schedule'|'source', value: string, all: readonly string[]) => { const current = filters[key]; const next = current.includes(value) ? current.filter(v => v !== value) : [...current, value]; setFilter(key, next.length ? next : [...all]); };
  return <div className={styles.toolbar}><input value={filters.search} onChange={e => setFilter('search', e.target.value)} placeholder="Search company, title, or location…" />{groups.map(group => <Multi key={group.key} label={group.label} open={open === group.key} toggleOpen={() => setOpen(open === group.key ? null : group.key)} values={group.values} selected={filters[group.key]} onChange={value => toggle(group.key, value, group.values)} />)}<Multi label="Source" open={open === 'source'} toggleOpen={() => setOpen(open === 'source' ? null : 'source')} values={sources} selected={filters.source} onChange={value => toggle('source', value, sources)} /><button className={filters.favOnly ? styles.active : ''} onClick={() => setFilter('favOnly', !filters.favOnly)}>★ Favorites ({favJobs.length + favEmployers.length})</button><button className={filters.showHidden ? styles.active : ''} onClick={() => setFilter('showHidden', !filters.showHidden)}>Hidden ({hiddenCount})</button><Multi label="Columns" open={open === 'columns'} toggleOpen={() => setOpen(open === 'columns' ? null : 'columns')} values={[...COLUMN_DEFAULTS.scanner]} selected={columns.scanner} onChange={value => setColumnVisibility('scanner', value, !columns.scanner.includes(value))} /><select defaultValue="" onChange={e => e.target.value && loadFilterPreset(e.target.value)}><option value="">Saved filters</option>{savedFilters.map(f => <option key={f.name}>{f.name}</option>)}</select><button onClick={() => { const name = window.prompt('Name this filter'); if (name?.trim()) saveFilterPreset(name.trim()); }}>+ Save</button>{savedFilters.length > 0 && <button onClick={() => { const name = window.prompt('Saved filter to delete'); if (name) deleteFilterPreset(name); }}>×</button>}</div>;
}
function Multi({ label, open, toggleOpen, values, selected, onChange }: { label: string; open: boolean; toggleOpen: () => void; values: readonly string[]; selected: string[]; onChange: (value: string) => void }) { return <div className={styles.multi}><button className={open ? styles.active : ''} onClick={toggleOpen}>{label}</button>{open && <div className={styles.menu}>{values.length ? values.map(value => <label key={value}><input type="checkbox" checked={selected.includes(value)} onChange={() => onChange(value)} />{value === 'posted_at' ? 'Posted' : value}</label>) : <span>No options yet</span>}</div>}</div>; }
