import type { Job } from '../../api/types'
import { useJobsStore } from '../../store/jobs'
import { usePreferencesStore } from '../../store/preferences'
import { useCompaniesStore } from '../../store/companies'
import { useApplicationsStore } from '../../store/applications'
import { timeAgo } from '../../utils/format'
import styles from './Scanner.module.css'
const labels: Record<string, string> = { company: 'Company', title: 'Title', location: 'Location', pay: 'Pay', posted_at: 'Posted', source: 'Source' }
export function JobTable({ jobs, total, onOpen, onHide, onFavorite, onEmployer, onTrack }: { jobs: Job[]; total: number; onOpen: (job: Job) => void; onHide: (id: string) => void | Promise<void>; onFavorite: (id: string) => void; onEmployer: (company: string) => void; onTrack: (job: Job) => Promise<string | number> }) { const { columns, sort, setSort } = usePreferencesStore(); const { hiddenIds, favJobIds } = useJobsStore(); const favEmployers = useCompaniesStore(s => s.favEmployers); const applications = useApplicationsStore((state) => state.items); return <><p className={styles.resultCount}>{jobs.length === total ? `${jobs.length} results` : `${jobs.length} of ${total} results`}</p><div className={styles.tableWrap}><table><thead><tr><th aria-label="Favorite" />{columns.scanner.map(column => <th key={column}><button onClick={() => setSort(column)}>{labels[column]} {sort.column === column && (sort.direction === 1 ? '▲' : '▼')}</button></th>)}<th aria-label="Actions" /></tr></thead><tbody>{jobs.map(job => { const hidden = hiddenIds.includes(job.id); const fav = favJobIds.includes(job.id); const employer = favEmployers.includes(job.company); const tracked = applications.some((app) => app.job_id === job.id); return <tr key={job.id} className={hidden ? styles.hiddenRow : ''}><td><button className={fav ? styles.favorited : ''} onClick={() => onFavorite(job.id)} aria-label={`Favorite ${job.title}`}>{fav ? '★' : '☆'}</button></td>{columns.scanner.map(column => <td key={column}>{cell(job, column, employer, () => onEmployer(job.company), () => onOpen(job))}</td>)}<td className={styles.rowActions}><button onClick={() => onOpen(job)}>Details</button><button onClick={() => void onTrack(job)} disabled={tracked}>{tracked ? 'Tracked' : 'Track'}</button><button onClick={() => void onHide(job.id)}>{hidden ? 'Unhide' : 'Hide'}</button></td></tr> })}</tbody></table>{!jobs.length && <div className={styles.noResults}>No jobs match these filters.</div>}</div></> }
function cell(job: Job, column: string, employer: boolean, favoriteEmployer: () => void, open: () => void) { switch (column) { case 'company': return <><button className={employer ? styles.employerFavorite : ''} onClick={favoriteEmployer} aria-label={`Favorite ${job.company}`}>♥</button>{job.company}{job.is_new && <span className={styles.newBadge}>NEW</span>}</>; case 'title': return <><span className={`${styles.level} ${styles[`level_${(job.level || 'mid').replace('+', 'plus')}`]}`}>{job.level || 'mid'}</span><button className={styles.titleButton} onClick={open}>{job.title}</button></>; case 'location': return job.location || '—'; case 'pay': return job.pay || '—'; case 'posted_at': return timeAgo(job.posted_at); case 'source': return <><span className={styles.source}>{job.source}</span>{job.schedule && <span className={styles.source}>{job.schedule}</span>}</>; default: return null } }
